version: "3.6"

services:
  flask:
    build: .
    container_name: weather-buddy-api
    environment:
      FLASK_APP: api
      FLASK_ENV: development
      DEBUG: "True"
      OPENWEATHERMAP_TOKEN: 3f62164f8ce1f8cb5ae8e2d02918babb
    ports:
      - 5000:5000
